<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>L04 — Conservation and Numerical Simulation – TKBM262615 Practicals</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../lecture_notes/L05-enzyme-kinetics-i/notes.html" rel="next">
<link href="../../lecture_notes/L03-reaction-networks-and-mass-action/notes.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-aced932c6eb97d642153b8e218288f9f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-98a61c67b863acd3c1a4826aa4ed5da3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../lecture_notes/L01-why-model-a-cell/notes.html">Lecture notes</a></li><li class="breadcrumb-item"><a href="../../lecture_notes/L04-conservation-and-numerical-simulation/notes.html"><span class="chapter-title">L04 — Conservation and Numerical Simulation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">TKBM262615 Practicals</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/lab-biotek-bio-ugm/TKBM262615_Practicals" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">TKBM262615 Practicals</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Lecture notes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lecture_notes/L01-why-model-a-cell/notes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L01 — Why Model a Cell?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lecture_notes/L02-the-mathematical-toolkit/notes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L02 — The Mathematical Toolkit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lecture_notes/L03-reaction-networks-and-mass-action/notes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L03 — Reaction Networks and Mass Action</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lecture_notes/L04-conservation-and-numerical-simulation/notes.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">L04 — Conservation and Numerical Simulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lecture_notes/L05-enzyme-kinetics-i/notes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L05 — Enzyme Kinetics I: the mechanism and the Michaelis-Menten equation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lecture_notes/L06-enzyme-kinetics-ii/notes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L06 — Enzyme Kinetics II: inhibition, cooperativity and soft switches</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Practical notebooks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notebooks/01_ode_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L01 — Introduction to Dynamic Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notebooks/02_mass_action.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L02 — Chemical Reaction Networks I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notebooks/02_simple_networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Simple Networks (MMSB §2.1.3)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notebooks/03_enzyme_kinetics_I.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L03 — Enzyme Kinetics I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notebooks/04_enzyme_kinetics_II.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L04 — Enzyme Kinetics II</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#retrieval-what-l03-left-you-holding" id="toc-retrieval-what-l03-left-you-holding" class="nav-link active" data-scroll-target="#retrieval-what-l03-left-you-holding">Retrieval: what L03 left you holding</a></li>
  <li><a href="#the-hook-count-the-molecules-not-the-concentrations" id="toc-the-hook-count-the-molecules-not-the-concentrations" class="nav-link" data-scroll-target="#the-hook-count-the-molecules-not-the-concentrations">The hook: count the molecules, not the concentrations</a></li>
  <li><a href="#part-1-conservation-in-a-closed-system" id="toc-part-1-conservation-in-a-closed-system" class="nav-link" data-scroll-target="#part-1-conservation-in-a-closed-system">Part 1 — Conservation in a closed system</a>
  <ul class="collapse">
  <li><a href="#what-the-word-closed-buys-you" id="toc-what-the-word-closed-buys-you" class="nav-link" data-scroll-target="#what-the-word-closed-buys-you">What the word “closed” buys you</a></li>
  <li><a href="#route-1-read-it-off-the-arrows" id="toc-route-1-read-it-off-the-arrows" class="nav-link" data-scroll-target="#route-1-read-it-off-the-arrows">Route 1 — read it off the arrows</a></li>
  <li><a href="#route-2-add-the-differential-equations" id="toc-route-2-add-the-differential-equations" class="nav-link" data-scroll-target="#route-2-add-the-differential-equations">Route 2 — add the differential equations</a></li>
  <li><a href="#conserved-concentration-is-not-conserved-mass" id="toc-conserved-concentration-is-not-conserved-mass" class="nav-link" data-scroll-target="#conserved-concentration-is-not-conserved-mass">Conserved concentration is not conserved mass</a></li>
  <li><a href="#structural-not-parametric" id="toc-structural-not-parametric" class="nav-link" data-scroll-target="#structural-not-parametric">Structural, not parametric</a></li>
  <li><a href="#the-biological-name-moiety-conservation" id="toc-the-biological-name-moiety-conservation" class="nav-link" data-scroll-target="#the-biological-name-moiety-conservation">The biological name: moiety conservation</a></li>
  <li><a href="#not-every-conservation-is-a-sum" id="toc-not-every-conservation-is-a-sum" class="nav-link" data-scroll-target="#not-every-conservation-is-a-sum">Not every conservation is a sum</a></li>
  </ul></li>
  <li><a href="#part-2-using-a-conservation-to-shrink-a-model" id="toc-part-2-using-a-conservation-to-shrink-a-model" class="nav-link" data-scroll-target="#part-2-using-a-conservation-to-shrink-a-model">Part 2 — Using a conservation to shrink a model</a>
  <ul class="collapse">
  <li><a href="#the-payoff-stated-as-a-payoff" id="toc-the-payoff-stated-as-a-payoff" class="nav-link" data-scroll-target="#the-payoff-stated-as-a-payoff">The payoff, stated as a payoff</a></li>
  <li><a href="#worked-example-the-reversible-pair" id="toc-worked-example-the-reversible-pair" class="nav-link" data-scroll-target="#worked-example-the-reversible-pair">Worked example — the reversible pair</a></li>
  <li><a href="#the-steady-state-falls-out" id="toc-the-steady-state-falls-out" class="nav-link" data-scroll-target="#the-steady-state-falls-out">The steady state falls out</a></li>
  <li><a href="#a-short-aside-what-a-steady-state-is" id="toc-a-short-aside-what-a-steady-state-is" class="nav-link" data-scroll-target="#a-short-aside-what-a-steady-state-is">A short aside: what a steady state is</a></li>
  <li><a href="#the-hinge-question" id="toc-the-hinge-question" class="nav-link" data-scroll-target="#the-hinge-question">The hinge question</a></li>
  <li><a href="#when-the-network-is-too-big-to-see" id="toc-when-the-network-is-too-big-to-see" class="nav-link" data-scroll-target="#when-the-network-is-too-big-to-see">When the network is too big to see</a></li>
  <li><a href="#the-word-exact-is-doing-real-work-here" id="toc-the-word-exact-is-doing-real-work-here" class="nav-link" data-scroll-target="#the-word-exact-is-doing-real-work-here">The word “exact” is doing real work here</a></li>
  </ul></li>
  <li><a href="#part-3-eulers-method" id="toc-part-3-eulers-method" class="nav-link" data-scroll-target="#part-3-eulers-method">Part 3 — Euler’s method</a>
  <ul class="collapse">
  <li><a href="#three-lectures-of-trusting-a-black-box" id="toc-three-lectures-of-trusting-a-black-box" class="nav-link" data-scroll-target="#three-lectures-of-trusting-a-black-box">Three lectures of trusting a black box</a></li>
  <li><a href="#what-a-solver-actually-computes" id="toc-what-a-solver-actually-computes" class="nav-link" data-scroll-target="#what-a-solver-actually-computes">What a solver actually computes</a></li>
  <li><a href="#the-derivation-in-three-lines" id="toc-the-derivation-in-three-lines" class="nav-link" data-scroll-target="#the-derivation-in-three-lines">The derivation, in three lines</a></li>
  <li><a href="#three-steps-by-hand" id="toc-three-steps-by-hand" class="nav-link" data-scroll-target="#three-steps-by-hand">Three steps by hand</a></li>
  <li><a href="#the-price-of-accuracy" id="toc-the-price-of-accuracy" class="nav-link" data-scroll-target="#the-price-of-accuracy">The price of accuracy</a></li>
  <li><a href="#euler-can-also-go-unstable" id="toc-euler-can-also-go-unstable" class="nav-link" data-scroll-target="#euler-can-also-go-unstable">Euler can also go unstable</a></li>
  <li><a href="#a-mesh-bug-worth-seeing-fail-once" id="toc-a-mesh-bug-worth-seeing-fail-once" class="nav-link" data-scroll-target="#a-mesh-bug-worth-seeing-fail-once">A mesh bug worth seeing fail once</a></li>
  </ul></li>
  <li><a href="#part-4-solving-odes-in-python" id="toc-part-4-solving-odes-in-python" class="nav-link" data-scroll-target="#part-4-solving-odes-in-python">Part 4 — Solving ODEs in Python</a>
  <ul class="collapse">
  <li><a href="#the-whole-call-with-nothing-hidden" id="toc-the-whole-call-with-nothing-hidden" class="nav-link" data-scroll-target="#the-whole-call-with-nothing-hidden">The whole call, with nothing hidden</a></li>
  <li><a href="#four-settings-worth-knowing" id="toc-four-settings-worth-knowing" class="nav-link" data-scroll-target="#four-settings-worth-knowing">Four settings worth knowing</a></li>
  <li><a href="#what-a-simulation-will-not-give-you" id="toc-what-a-simulation-will-not-give-you" class="nav-link" data-scroll-target="#what-a-simulation-will-not-give-you">What a simulation will not give you</a></li>
  <li><a href="#this-weeks-practical" id="toc-this-weeks-practical" class="nav-link" data-scroll-target="#this-weeks-practical">This week’s practical</a></li>
  <li><a href="#three-sentences-to-carry-into-l05" id="toc-three-sentences-to-carry-into-l05" class="nav-link" data-scroll-target="#three-sentences-to-carry-into-l05">Three sentences to carry into L05</a></li>
  <li><a href="#sources" id="toc-sources" class="nav-link" data-scroll-target="#sources">Sources</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/lab-biotek-bio-ugm/TKBM262615_Practicals/blob/main/lecture_notes/L04-conservation-and-numerical-simulation/notes.md" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../lecture_notes/L01-why-model-a-cell/notes.html">Lecture notes</a></li><li class="breadcrumb-item"><a href="../../lecture_notes/L04-conservation-and-numerical-simulation/notes.html"><span class="chapter-title">L04 — Conservation and Numerical Simulation</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">L04 — Conservation and Numerical Simulation</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Practical:</strong> <a href="https://colab.research.google.com/github/lab-biotek-bio-ugm/TKBM262615_Practicals/blob/main/notebooks/02_simple_networks.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" class="img-fluid" alt="Open In Colab"></a> <code>02_simple_networks</code></p>
<p><em>TKBM262615, Lecture 4. Draws on conservation relation, nullspace, steady state, numerical simulation, and simulation versus analysis. Source: Ingalls Ch. 2, §2.1.3 and §2.1.4. Companion practical: <code>notebooks/02_simple_networks.ipynb</code> (Examples II–V, Exercises 1–4).</em></p>
<blockquote class="blockquote">
<p><strong>Bahasa Indonesia:</strong> <a href="notes.id.md"><code>notes.id.md</code></a>. The two versions carry the same material, the same equations and the same numbers; read whichever you think in.</p>
</blockquote>
<p>By the end of this lecture you should be able to:</p>
<ol type="1">
<li>State what a conservation relation is, find one in a small closed network by two different routes, and say why it holds for every value of the rate constants.</li>
<li>Use a conservation to eliminate one differential equation <strong>exactly</strong>, then find the steady state algebraically.</li>
<li>Derive Euler’s method from the definition of the derivative, take three steps by hand, and say where the error comes from and how it shrinks with the step size.</li>
<li>Integrate a reaction-network model with <code>scipy.integrate.solve_ivp</code>, set tolerances deliberately, and say what a simulation cannot tell you that a formula can.</li>
</ol>
<p>There is one sentence to carry from the start, because it is the spine of this lecture and the bridge into L05: <strong>reduction by conservation is exact.</strong> Nothing is approximated. Next week you will meet another reduction that looks identical on the page and is a bet. That difference matters far more than it looks.</p>
<section id="retrieval-what-l03-left-you-holding" class="level2">
<h2 class="anchored" data-anchor-id="retrieval-what-l03-left-you-holding">Retrieval: what L03 left you holding</h2>
<p>Answer from memory, notes closed:</p>
<ol type="1">
<li>Why is the rate for <span class="math inline">\(A + B \to C\)</span> a product, <span class="math inline">\(k[A][B]\)</span>, rather than a sum?</li>
<li>A network has five species and three reactions. How many differential equations?</li>
<li>What are the units of <span class="math inline">\(k\)</span> in a second-order rate law?</li>
</ol>
<details>
<summary>
Answers
</summary>
<ol type="1">
<li>The rate is proportional to the chance that one molecule of A collides with one molecule of B. The probability of two independent events happening together is the product of their probabilities, not the sum.</li>
<li>Five. One per species, whatever the number of reactions. Reactions contribute <em>terms</em>, not equations.</li>
<li><span class="math inline">\(\text{concentration}^{-1}\,\text{time}^{-1}\)</span>. Check it dimensionally: the left side <span class="math inline">\(\frac{d[C]}{dt}\)</span> is concentration per time, and the right side <span class="math inline">\(k[A][B]\)</span> is <span class="math inline">\([k] \times \text{concentration}^2\)</span>.</li>
</ol>
</details>
</section>
<section id="the-hook-count-the-molecules-not-the-concentrations" class="level2">
<h2 class="anchored" data-anchor-id="the-hook-count-the-molecules-not-the-concentrations">The hook: count the molecules, not the concentrations</h2>
<p>Take the irreversible conversion <span class="math inline">\(A \xrightarrow{k} B\)</span>. Every time a molecule of B appears, a molecule of A has disappeared. Nothing enters the beaker and nothing leaves it.</p>
<p>So the total cannot move.</p>
<p>That is the whole concept. The rest of this section is how to write it down, how to find it when the network is too complicated to see, and what it buys you.</p>
<hr>
</section>
<section id="part-1-conservation-in-a-closed-system" class="level1">
<h1>Part 1 — Conservation in a closed system</h1>
<section id="what-the-word-closed-buys-you" class="level2">
<h2 class="anchored" data-anchor-id="what-the-word-closed-buys-you">What the word “closed” buys you</h2>
<p>A <strong>closed</strong> network has no inflow, no outflow, no synthesis and no degradation. All that happens is that material is passed around among the species inside it.</p>
<p><strong>Every closed network has at least one conservation relation.</strong> The phrase “at least one” is doing work: a closed network with five species may well have two or three independent conservations. An <strong>open</strong> network may or may not have one, and you are not entitled to assume it.</p>
</section>
<section id="route-1-read-it-off-the-arrows" class="level2">
<h2 class="anchored" data-anchor-id="route-1-read-it-off-the-arrows">Route 1 — read it off the arrows</h2>
<p>Look at what gets passed along unchanged. For <span class="math inline">\(A \to B\)</span>, every event moves one molecule from A to B, so <span class="math inline">\(A + B\)</span> is fixed.</p>
<p>This route is fast and intuitive, and it will not last. Once the network has ten species and fifteen arrows you will not see it. That is why the second route is the one you keep for life.</p>
</section>
<section id="route-2-add-the-differential-equations" class="level2">
<h2 class="anchored" data-anchor-id="route-2-add-the-differential-equations">Route 2 — add the differential equations</h2>
<p>Write the model with mass action, exactly as in L03:</p>
<p><span class="math display">\[\frac{d[A]}{dt} = -k[A], \qquad \frac{d[B]}{dt} = +k[A]\]</span></p>
<p>Now add them. Add the left sides, add the right sides:</p>
<p><span class="math display">\[\frac{d}{dt}\left(a(t) + b(t)\right) = \frac{da}{dt} + \frac{db}{dt} = -ka + ka = 0\]</span></p>
<p>A quantity whose derivative is zero for all time is a constant. So:</p>
<p><span class="math display">\[a(t) + b(t) = T \quad \text{for all } t, \qquad T = A_0 + B_0\]</span></p>
<p>Notice where <span class="math inline">\(T\)</span> comes from: the <strong>initial conditions</strong>, not the rate constants. That is what makes <span class="math inline">\(T\)</span> useful — it is a number you already know before any simulation is run.</p>
<p>Watching the same answer arrive twice, once through chemistry and once through algebra, is what makes the algebraic route believable later, when the chemistry is too complicated to eyeball.</p>
</section>
<section id="conserved-concentration-is-not-conserved-mass" class="level2">
<h2 class="anchored" data-anchor-id="conserved-concentration-is-not-conserved-mass">Conserved concentration is not conserved mass</h2>
<p>This is the main misconception on this topic, and the syllabus’s own phrase “mass conservation” invites it.</p>
<p>What is conserved in <span class="math inline">\(a + b = T\)</span> is a <strong>count of molecules</strong>, or equivalently a concentration. Is mass conserved? Only if A and B have the same molecular mass, and they need not. Ingalls separates the two terms deliberately (p.&nbsp;29), and that care is worth passing on.</p>
<blockquote class="blockquote">
<p>Ask yourself: what does <span class="math inline">\(ATP \to ADP + P_i\)</span> conserve? The count of adenine groups, yes. Total mass in a closed system, yes as well, since nothing leaves. But the concentration of ATP alone, clearly not.</p>
</blockquote>
</section>
<section id="structural-not-parametric" class="level2">
<h2 class="anchored" data-anchor-id="structural-not-parametric">Structural, not parametric</h2>
<p>Does the conservation <span class="math inline">\(a + b = T\)</span> depend on the value of <span class="math inline">\(k\)</span>?</p>
<p>No.&nbsp;It holds for <strong>every</strong> <span class="math inline">\(k\)</span>. Look back at the derivation: <span class="math inline">\(k\)</span> appeared in both terms and then cancelled. A conservation is a property of <strong>which arrows exist</strong>, not of how fast they run.</p>
<p>This is what a <strong>structural conservation</strong> means, and it is the seed of everything Ch. 5 does with metabolic network structure. The practical consequence is large: you can trust a conservation in a model whose rate constants nobody has ever measured.</p>
</section>
<section id="the-biological-name-moiety-conservation" class="level2">
<h2 class="anchored" data-anchor-id="the-biological-name-moiety-conservation">The biological name: moiety conservation</h2>
<p>A <strong>moiety</strong> is a group of atoms forming part of a molecule. Many chemical conservations are <strong>moiety conservations</strong>: some chemical group is passed between molecules without ever being created or destroyed.</p>
<p>Examples you already know from biochemistry:</p>
<ul>
<li><strong>Adenine nucleotides.</strong> <span class="math inline">\([ATP] + [ADP] + [AMP]\)</span> is effectively fixed on a timescale of minutes. What moves is the phosphate group.</li>
<li><strong>Redox cofactors.</strong> <span class="math inline">\([NAD^+] + [NADH]\)</span> is fixed; what moves is electrons.</li>
<li><strong>Enzymes.</strong> An enzyme is not consumed by the reaction it catalyses, so total enzyme is fixed. This is the one that saves the Michaelis-Menten derivation next week. Remember it.</li>
</ul>
</section>
<section id="not-every-conservation-is-a-sum" class="level2">
<h2 class="anchored" data-anchor-id="not-every-conservation-is-a-sum">Not every conservation is a sum</h2>
<p>You will be tempted to generalise “a conservation is the sum of two concentrations”. Do not.</p>
<p>Ingalls Exercise 2.1.8 gives a system in which one reaction produces C and D <strong>together</strong>. Because they are always born in pairs, what stays fixed is their <strong>difference</strong>, <span class="math inline">\(c - d\)</span>, not their sum.</p>
<p>Look for <strong>combinations</strong>, not totals. Route 2 will find them for you; Route 1 will not.</p>
<hr>
</section>
</section>
<section id="part-2-using-a-conservation-to-shrink-a-model" class="level1">
<h1>Part 2 — Using a conservation to shrink a model</h1>
<section id="the-payoff-stated-as-a-payoff" class="level2">
<h2 class="anchored" data-anchor-id="the-payoff-stated-as-a-payoff">The payoff, stated as a payoff</h2>
<p>Systems of differential equations are much harder than single differential equations. That is not just a feeling — in L03 you already saw that nonlinear models generally have no explicit solution at all.</p>
<p>A conservation hands you one fewer equation, free:</p>
<blockquote class="blockquote">
<p><strong>Two differential equations</strong> become <strong>one differential equation plus one line of arithmetic.</strong></p>
</blockquote>
<p>Solve for <span class="math inline">\(a(t)\)</span>, then read <span class="math inline">\(b(t) = T - a(t)\)</span> off without solving anything further.</p>
</section>
<section id="worked-example-the-reversible-pair" class="level2">
<h2 class="anchored" data-anchor-id="worked-example-the-reversible-pair">Worked example — the reversible pair</h2>
<p>Take <span class="math inline">\(A \rightleftharpoons B\)</span> with forward constant <span class="math inline">\(k_+\)</span> and reverse <span class="math inline">\(k_-\)</span>:</p>
<p><span class="math display">\[\frac{da}{dt} = k_-b - k_+a, \qquad \frac{db}{dt} = k_+a - k_-b\]</span></p>
<p>The two derivatives are exact negatives, so <span class="math inline">\(a + b = T\)</span> again, by Route 2.</p>
<p>Now use it. Substitute <span class="math inline">\(b = T - a\)</span> into the first equation:</p>
<p><span class="math display">\[\frac{da}{dt} = k_-(T - a) - k_+a = k_-T - (k_+ + k_-)a \tag{2.12}\]</span></p>
<p>Two coupled equations have become one, in one unknown. Look at its shape: this is <strong>exactly</strong> the production-and-decay model you solved in L03 and in <code>02_simple_networks.ipynb</code>, Example II, with <span class="math inline">\(k_-T\)</span> as the production rate and <span class="math inline">\((k_+ + k_-)\)</span> as the decay constant. A network that looked new turns out to be an old one in disguise.</p>
</section>
<section id="the-steady-state-falls-out" class="level2">
<h2 class="anchored" data-anchor-id="the-steady-state-falls-out">The steady state falls out</h2>
<p>Set the derivative to zero and solve. This is <strong>algebra, not calculus</strong> — you never touch the differential equation:</p>
<p><span class="math display">\[0 = k_-T - (k_+ + k_-)a^{ss} \quad\Longrightarrow\quad
a^{ss} = \frac{k_-T}{k_+ + k_-}, \qquad b^{ss} = \frac{k_+T}{k_+ + k_-} \tag{2.13}\]</span></p>
<p><strong>Check:</strong> <span class="math inline">\(a^{ss} + b^{ss} = \frac{(k_- + k_+)T}{k_+ + k_-} = T\)</span>. It has to be — a conservation holds at steady state as it does everywhere else. Say that check out loud as a <strong>requirement</strong>, not as a pleasant coincidence.</p>
<p>Notice also that only the <strong>ratio</strong> <span class="math inline">\(k_+/k_-\)</span> sets the split. Double both and the answer does not move. That is exactly what <code>02_simple_networks.ipynb</code>, Example IV, shows numerically, and it is what the hinge question below tests.</p>
</section>
<section id="a-short-aside-what-a-steady-state-is" class="level2">
<h2 class="anchored" data-anchor-id="a-short-aside-what-a-steady-state-is">A short aside: what a steady state is</h2>
<p>One paragraph, because the hinge question needs it and L05 needs it. The full treatment is Ch. 4, outside this course.</p>
<p><span class="math display">\[f(\mathbf{x}^{ss}, \mathbf{p}) = 0\]</span></p>
<p>This says: <strong>the rate of change of every concentration is zero, all at once.</strong> It does not say the reactions stopped. On <span class="math inline">\(\to A \to\)</span> with production <span class="math inline">\(k_0\)</span> and decay <span class="math inline">\(k_1\)</span>, the steady state is <span class="math inline">\(a^{ss} = k_0/k_1\)</span>, and both reactions are running at rate <span class="math inline">\(k_0\)</span> — equal, opposite, and not remotely zero. Nothing is changing and everything is happening.</p>
<p>Three caveats worth naming once and then leaving: a steady state can exist without ever being reached on any relevant timescale; it can be unstable, a state the system leaves; and there can be more than one.</p>
</section>
<section id="the-hinge-question" class="level2">
<h2 class="anchored" data-anchor-id="the-hinge-question">The hinge question</h2>
<p>The closed network <span class="math inline">\(A \rightleftharpoons B\)</span> starts at <span class="math inline">\(a(0) = 3\)</span> mM, <span class="math inline">\(b(0) = 1\)</span> mM. Someone doubles <strong>both</strong> <span class="math inline">\(k_+\)</span> and <span class="math inline">\(k_-\)</span>. Which statement is true of the new steady state?</p>
<ul>
<li><strong>A.</strong> <span class="math inline">\(T\)</span> changes, <span class="math inline">\(a^{ss}\)</span> does not.</li>
<li><strong>B.</strong> Neither <span class="math inline">\(T\)</span> nor <span class="math inline">\(a^{ss}\)</span> changes.</li>
<li><strong>C.</strong> <span class="math inline">\(T\)</span> holds, but <span class="math inline">\(a^{ss}\)</span> changes.</li>
<li><strong>D.</strong> Both change.</li>
</ul>
<details>
<summary>
Answer and reasoning
</summary>
<p><strong>B.</strong></p>
<p><span class="math inline">\(T = A_0 + B_0 = 4\)</span> mM, set by the initial conditions. The rate constants do not touch it at all — they cancelled out of the derivation.</p>
<p>And <span class="math inline">\(a^{ss} = \frac{k_-T}{k_+ + k_-}\)</span>. Double <span class="math inline">\(k_+\)</span> and <span class="math inline">\(k_-\)</span>: the numerator becomes <span class="math inline">\(2k_-T\)</span>, the denominator becomes <span class="math inline">\(2(k_+ + k_-)\)</span>, and the factor of two cancels. Only the ratio matters.</p>
<p><strong>A</strong> thinks rate constants can move a conserved total. <strong>C</strong> is the most common and most instructive wrong answer: it gets the structural half right, then assumes that changing a parameter must change the answer. <strong>D</strong> makes both errors.</p>
<p>What <em>does</em> change when you double both constants is the <strong>speed</strong> at which the system reaches that steady state — the time constant <span class="math inline">\(1/(k_+ + k_-)\)</span> halves. Same destination, twice as fast.</p>
</details>
</section>
<section id="when-the-network-is-too-big-to-see" class="level2">
<h2 class="anchored" data-anchor-id="when-the-network-is-too-big-to-see">When the network is too big to see</h2>
<p>Route 2 is really a linear-algebra computation, and once you see it that way it runs on a network of any size.</p>
<p>Build the <strong>stoichiometry matrix</strong> <span class="math inline">\(\mathbf{N}\)</span>: rows are species, columns are reactions, entries are how many molecules of each species each reaction makes or consumes. For <span class="math inline">\(A \to B\)</span>, two species and one reaction:</p>
<p><span class="math display">\[\mathbf{N} = \begin{pmatrix} -1 \\ +1 \end{pmatrix}\]</span></p>
<p>Now look for a vector of weights <span class="math inline">\(\mathbf{w}\)</span> such that:</p>
<p><span class="math display">\[\mathbf{w}^{T}\mathbf{N} = 0 \quad\Longleftrightarrow\quad \frac{d}{dt}(\mathbf{w}\cdot\mathbf{x}) = 0\]</span></p>
<p>Read the left side as a sentence: <strong>find the weighted combinations that no reaction disturbs.</strong> If nothing changes it, it is constant, and that is the definition of a conservation.</p>
<p>The set of such vectors is the <strong>left nullspace</strong> of <span class="math inline">\(\mathbf{N}\)</span> — which is where the nullspace you met in L02 finally earns its place.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># /// script</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># dependencies = ["numpy", "scipy"]</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ///</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">"""Finding a conservation from network structure rather than by guessing."""</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.linalg <span class="im">import</span> null_space</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># A -&gt; B: two species (rows), one reaction (column)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> np.array([[<span class="op">-</span><span class="fl">1.0</span>],</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>              [<span class="op">+</span><span class="fl">1.0</span>]])</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(null_space(N.T).ravel())     <span class="co"># [0.707 0.707]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The answer is <span class="math inline">\([0.707,\ 0.707]\)</span> rather than <span class="math inline">\([1,\ 1]\)</span> because <code>null_space</code> normalises what it returns. What carries meaning is the <strong>direction</strong>, not the scale: <span class="math inline">\([0.707, 0.707]\)</span> is proportional to <span class="math inline">\([1, 1]\)</span>, which reads “<span class="math inline">\(a + b\)</span>”. Multiply by <span class="math inline">\(\sqrt{2}\)</span> if you want to see it.</p>
<p>One honest limitation, which the practical explores: beyond a single conservation, <code>null_space</code> returns an arbitrary basis for the space, and its vectors are usually mixtures with no chemical meaning. The computation tells you <em>how many</em> independent conservations exist, which is the hard part. Deciding which combinations are worth naming is chemistry, and <code>w @ N == 0</code> is how you check a candidate once you have one.</p>
</section>
<section id="the-word-exact-is-doing-real-work-here" class="level2">
<h2 class="anchored" data-anchor-id="the-word-exact-is-doing-real-work-here">The word “exact” is doing real work here</h2>
<p>Nothing in this reduction is approximated. The reduced model <strong>is the same model</strong>, written shorter. Integrate the full system and the reduced system with tight tolerances and they will agree to the limit of what the solver can do.</p>
<p>More than that: the conservation <strong>survives simulation to machine precision</strong>. The reason is worth a moment. The solver computes both derivatives from the same expression, and that expression makes them exact negatives at every step. Whatever is added to one species is subtracted from the other, by an identical floating-point number. So <span class="math inline">\(a + b\)</span> never budges.</p>
<p>Notice what that argument did <strong>not</strong> mention: accuracy. It holds for crude Euler exactly as it holds for a good solver. A conservation is a structural property, and structure does not care about step size. (This week’s Level 3 problem asks you about precisely this.)</p>
<p>Bank the sentence. Next week you will meet a reduction that looks identical on the board and produces a <strong>different</strong> model.</p>
<hr>
</section>
</section>
<section id="part-3-eulers-method" class="level1">
<h1>Part 3 — Euler’s method</h1>
<section id="three-lectures-of-trusting-a-black-box" class="level2">
<h2 class="anchored" data-anchor-id="three-lectures-of-trusting-a-black-box">Three lectures of trusting a black box</h2>
<p>Since L01 you have called <code>solve_ivp</code> and accepted the curve that came out. Today the box opens.</p>
<p>Why numerical simulation is necessary at all, in Ingalls’ own words: differential equation models of biochemical and genetic systems are <strong>invariably nonlinear</strong>, and nonlinear models do not typically admit explicit solutions. This is not a failure of cleverness. There is no formula.</p>
</section>
<section id="what-a-solver-actually-computes" class="level2">
<h2 class="anchored" data-anchor-id="what-a-solver-actually-computes">What a solver actually computes</h2>
<p>A numerical solver does <strong>not</strong> compute a function. It computes a list of numbers: the concentration at <span class="math inline">\(t = 0\)</span>, at <span class="math inline">\(t = h\)</span>, at <span class="math inline">\(t = 2h\)</span>, and so on. The first step is choosing that <strong>mesh</strong> of time points. Then you need an <strong>update formula</strong> to get from one to the next.</p>
<p>The simplest one is Euler’s method, and it comes straight from the definition of the derivative.</p>
</section>
<section id="the-derivation-in-three-lines" class="level2">
<h2 class="anchored" data-anchor-id="the-derivation-in-three-lines">The derivation, in three lines</h2>
<p>Recall from L02 that the derivative is the limit of a difference quotient. For small <span class="math inline">\(h\)</span> it is approximately that quotient:</p>
<p><span class="math display">\[\frac{d}{dt}a(t) \;\approx\; \frac{a(t+h) - a(t)}{h}\]</span></p>
<p>Substitute it into the model <span class="math inline">\(\frac{da}{dt} = f(a)\)</span>:</p>
<p><span class="math display">\[\frac{a(t+h) - a(t)}{h} \;\approx\; f(a(t))\]</span></p>
<p>Now <strong>treat the approximation as an equality</strong> and rearrange:</p>
<p><span class="math display">\[a(t+h) = a(t) + h\,f(a(t)) \tag{2.16}\]</span></p>
<p>That last line is the whole trick, and the step from <span class="math inline">\(\approx\)</span> to <span class="math inline">\(=\)</span> is where <strong>all</strong> of the error enters. There is no other source of error in the method.</p>
<p>Read the result as a sentence, not as symbols:</p>
<blockquote class="blockquote">
<p>The new value is the old value, plus the step size times the rate of change at the old value.</p>
</blockquote>
<p>A student who can say that sentence has understood Euler’s method. The rest is arithmetic.</p>
<p>What it assumes: <strong>the rate holds constant across the step.</strong> It does not. That is the error.</p>
</section>
<section id="three-steps-by-hand" class="level2">
<h2 class="anchored" data-anchor-id="three-steps-by-hand">Three steps by hand</h2>
<p>Do this on paper before reading the answer. Take <span class="math inline">\(\frac{da}{dt} = -a\)</span> with <span class="math inline">\(a(0) = 1\)</span> and <span class="math inline">\(h = 2/3\)</span>, and run three steps to <span class="math inline">\(t = 2\)</span>.</p>
<p>The arithmetic</p>
<p><span class="math display">\[a(2/3) = 1 + \tfrac{2}{3}(-1) = \tfrac{1}{3}\]</span> <span class="math display">\[a(4/3) = \tfrac{1}{3} + \tfrac{2}{3}\left(-\tfrac{1}{3}\right) = \tfrac{1}{9}\]</span> <span class="math display">\[a(2) = \tfrac{1}{9} + \tfrac{2}{3}\left(-\tfrac{1}{9}\right) = \tfrac{1}{27} = 0.037\]</span></p>
<p>The exact value is <span class="math inline">\(e^{-2} = 0.135\)</span>. Your approximation is <strong>73%</strong> low.</p>
<p>Seeing your own bad approximation is worth more than any warning about the limits of numerical methods.</p>
</section>
<section id="the-price-of-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="the-price-of-accuracy">The price of accuracy</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># /// script</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># dependencies = ["numpy", "scipy"]</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ///</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">"""Euler by hand against solve_ivp, on the one model we can solve exactly."""</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.integrate <span class="im">import</span> solve_ivp</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> euler(f, y0, t_end, h):</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Ingalls' equation (2.16), applied repeatedly."""</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">int</span>(<span class="bu">round</span>(t_end <span class="op">/</span> h))          <span class="co"># NOT np.arange(0, t_end + h, h) -- see the note below</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    ts <span class="op">=</span> np.linspace(<span class="dv">0</span>, t_end, n <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    ys <span class="op">=</span> np.empty_like(ts)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    ys[<span class="dv">0</span>] <span class="op">=</span> y0</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n):</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        ys[i <span class="op">+</span> <span class="dv">1</span>] <span class="op">=</span> ys[i] <span class="op">+</span> h <span class="op">*</span> f(ys[i])</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ts, ys</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> <span class="kw">lambda</span> a: <span class="op">-</span>a                        <span class="co"># da/dt = -a, so the exact answer is exp(-t)</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>exact <span class="op">=</span> np.exp(<span class="op">-</span><span class="fl">2.0</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> h <span class="kw">in</span> (<span class="dv">2</span> <span class="op">/</span> <span class="dv">3</span>, <span class="dv">1</span> <span class="op">/</span> <span class="dv">3</span>, <span class="dv">1</span> <span class="op">/</span> <span class="dv">30</span>):</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    _, ys <span class="op">=</span> euler(f, <span class="fl">1.0</span>, <span class="fl">2.0</span>, h)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"h=</span><span class="sc">{</span>h<span class="sc">:6.4f}</span><span class="ss">  euler=</span><span class="sc">{</span>ys[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.6f}</span><span class="ss">  exact=</span><span class="sc">{</span>exact<span class="sc">:.6f}</span><span class="ss">  error=</span><span class="sc">{</span><span class="bu">abs</span>(ys[<span class="op">-</span><span class="dv">1</span>] <span class="op">-</span> exact)<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>ref <span class="op">=</span> solve_ivp(<span class="kw">lambda</span> t, y: [<span class="op">-</span>y[<span class="dv">0</span>]], [<span class="dv">0</span>, <span class="dv">2</span>], [<span class="fl">1.0</span>], rtol<span class="op">=</span><span class="fl">1e-12</span>, atol<span class="op">=</span><span class="fl">1e-14</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"solve_ivp  error=</span><span class="sc">{</span><span class="bu">abs</span>(ref.y[<span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>] <span class="op">-</span> exact)<span class="sc">:.2e}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Output:</p>
<pre><code>h=0.6667  euler=0.037037  exact=0.135335  error=0.098298
h=0.3333  euler=0.087791  exact=0.135335  error=0.047544
h=0.0333  euler=0.130799  exact=0.135335  error=0.004536
solve_ivp  error=5.75e-14</code></pre>
<p>Two things to draw out of those numbers.</p>
<p><strong>Halving <span class="math inline">\(h\)</span> halves the error.</strong> From 0.0983 to 0.0475. That is what “first-order method” means, and it is a bad deal: ten times the work for ten times the accuracy. To gain three more digits you would run a thousand times as many steps.</p>
<p><strong><code>solve_ivp</code> is twelve orders of magnitude better</strong> than Euler at <span class="math inline">\(h = 1/30\)</span>, because it uses a higher-order method with an adaptive step size. Euler is for <strong>understanding</strong>, not for using.</p>
</section>
<section id="euler-can-also-go-unstable" class="level2">
<h2 class="anchored" data-anchor-id="euler-can-also-go-unstable">Euler can also go unstable</h2>
<p>If <span class="math inline">\(h\)</span> is too large the numerical answer oscillates or grows, while the true solution decays quietly the whole time. Try <span class="math inline">\(\frac{da}{dt} = -a\)</span> with <span class="math inline">\(h = 2.5\)</span>: the values alternate in sign and grow without bound.</p>
<p>That is a property of the <strong>method</strong>, not of the biology. It is also why real solvers choose their own step size rather than leaving it to you.</p>
</section>
<section id="a-mesh-bug-worth-seeing-fail-once" class="level2">
<h2 class="anchored" data-anchor-id="a-mesh-bug-worth-seeing-fail-once">A mesh bug worth seeing fail once</h2>
<p>The obvious way to build the mesh, <code>np.arange(0, t_end + h, h)</code>, is <strong>wrong</strong>.</p>
<p>With <span class="math inline">\(h = 1/3\)</span> and <span class="math inline">\(t_{end} = 2\)</span>, floating-point rounding lets <code>arange</code> emit a final point at <span class="math inline">\(t = 2.333\)</span>. Your loop takes <strong>seven</strong> steps instead of six and reports the concentration at the wrong time.</p>
<p>The symptom is subtle, which is what makes it dangerous: the answer is still a plausible number, and the error <strong>stops halving</strong> when you halve <span class="math inline">\(h\)</span>. That looks like a property of the method rather than a bug.</p>
<p>The rule is one sentence: <strong>never build a floating-point mesh with <code>arange</code>.</strong> <code>np.linspace(0, t_end, n + 1)</code> with an integer <span class="math inline">\(n\)</span> lands on <span class="math inline">\(t_{end}\)</span> exactly.</p>
<hr>
</section>
</section>
<section id="part-4-solving-odes-in-python" class="level1">
<h1>Part 4 — Solving ODEs in Python</h1>
<section id="the-whole-call-with-nothing-hidden" class="level2">
<h2 class="anchored" data-anchor-id="the-whole-call-with-nothing-hidden">The whole call, with nothing hidden</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># /// script</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># dependencies = ["numpy", "scipy", "matplotlib"]</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ///</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">"""Closed A &lt;-&gt; B: the full model, the reduced model, and the conservation check."""</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.integrate <span class="im">import</span> solve_ivp</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>kp, km <span class="op">=</span> <span class="fl">0.8</span>, <span class="fl">0.2</span>          <span class="co"># k+ and k- in 1/s</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>A0, B0 <span class="op">=</span> <span class="fl">3.0</span>, <span class="fl">1.0</span>          <span class="co"># mM</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>T <span class="op">=</span> A0 <span class="op">+</span> B0</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> reversible(t, y, kp, km):</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Right-hand side of the full model. Time first, even though the model ignores it."""</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    a, b <span class="op">=</span> y</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [<span class="op">-</span>kp <span class="op">*</span> a <span class="op">+</span> km <span class="op">*</span> b,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>            kp <span class="op">*</span> a <span class="op">-</span> km <span class="op">*</span> b]</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> reduced(t, y, kp, km, T):</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Equation (2.12): one equation, because b = T - a."""</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    a <span class="op">=</span> y[<span class="dv">0</span>]</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [km <span class="op">*</span> (T <span class="op">-</span> a) <span class="op">-</span> kp <span class="op">*</span> a]</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>tol <span class="op">=</span> <span class="bu">dict</span>(rtol<span class="op">=</span><span class="fl">1e-8</span>, atol<span class="op">=</span><span class="fl">1e-10</span>, dense_output<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>full <span class="op">=</span> solve_ivp(reversible, [<span class="dv">0</span>, <span class="dv">20</span>], [A0, B0], args<span class="op">=</span>(kp, km), <span class="op">**</span>tol)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>red <span class="op">=</span> solve_ivp(reduced, [<span class="dv">0</span>, <span class="dv">20</span>], [A0], args<span class="op">=</span>(kp, km, T), <span class="op">**</span>tol)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">20</span>, <span class="dv">200</span>)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>a_full, b_full <span class="op">=</span> full.sol(t)</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>a_red <span class="op">=</span> red.sol(t)[<span class="dv">0</span>]</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"conservation held to </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">max</span>(np.<span class="bu">abs</span>(a_full <span class="op">+</span> b_full <span class="op">-</span> T))<span class="sc">:.2e}</span><span class="ss"> mM"</span>)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"full vs reduced agree to </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">max</span>(np.<span class="bu">abs</span>(a_full <span class="op">-</span> a_red))<span class="sc">:.2e}</span><span class="ss"> mM"</span>)</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"steady state: theory a=</span><span class="sc">{</span>km <span class="op">*</span> T <span class="op">/</span> (kp <span class="op">+</span> km)<span class="sc">:.4f}</span><span class="ss">, numeric a=</span><span class="sc">{</span>a_full[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Output:</p>
<pre><code>conservation held to 8.88e-16 mM
full vs reduced agree to 5.25e-09 mM
steady state: theory a=0.8000, numeric a=0.8000</code></pre>
<p>Notice that the two check numbers differ by <strong>seven orders of magnitude</strong>, and that this is not an accident. The conservation holds to machine precision (<span class="math inline">\(10^{-16}\)</span>) because it is structural. The agreement between two separate integrations is only as good as the tolerance you asked for (<span class="math inline">\(10^{-8}\)</span>). An exact structural property stays exact under simulation; a numerical agreement is only as good as you paid for.</p>
</section>
<section id="four-settings-worth-knowing" class="level2">
<h2 class="anchored" data-anchor-id="four-settings-worth-knowing">Four settings worth knowing</h2>
<p><strong><code>args</code></strong> — pass parameters as arguments, not as globals. A model with global parameters cannot be reused and cannot be swept.</p>
<p><strong><code>dense_output=True</code></strong> — gives you <code>sol.sol(t)</code> at any <span class="math inline">\(t\)</span>, not only at the points the solver happened to choose. This decouples “where the solver stepped” from “where I want to plot”, which really are different questions.</p>
<p><strong><code>rtol</code>, <code>atol</code></strong> — the default is <code>rtol=1e-3</code>, and that is loose. Two independent integrations of the same system can disagree in the fourth decimal place at the defaults. Neither has a bug. <strong>Set tolerances whenever you intend to compare two results.</strong></p>
<p><strong><code>method</code></strong> — if a simulation is inexplicably slow, or the solver is taking tiny steps, the system may be <strong>stiff</strong>: very different time constants in one model. Try <code>method="LSODA"</code> or <code>method="Radau"</code>. Stiffness is not covered in Ch. 2, but you will hit it next week on the enzyme-substrate complex. Recognising the name is enough for now.</p>
<p>One note on the signature: <code>rhs(t, y, *args)</code> — <strong>time first</strong>, even when the model does not use time at all. This is the most common source of confusing errors for beginners. And use <code>solve_ivp</code> rather than the older <code>odeint</code>; the argument order differs and the interface is worse.</p>
</section>
<section id="what-a-simulation-will-not-give-you" class="level2">
<h2 class="anchored" data-anchor-id="what-a-simulation-will-not-give-you">What a simulation will not give you</h2>
<p>Ingalls gives this a full paragraph, and it deserves the same weight in your head. Students who have just learned to call a solver conclude that simulation supersedes algebra. It does not.</p>
<ol type="1">
<li><strong>One simulation run is one initial condition.</strong> An analytic formula covers all of them at once. Want a different starting point? Run it again.</li>
<li><strong>A formula shows the parameter dependence.</strong> From <span class="math inline">\(a^{ss} = k_0/k_1\)</span> you read straight off that doubling <span class="math inline">\(k_0\)</span> doubles the steady state. A simulation fixes the parameters, so exploring them means running many simulations and inferring the pattern — and inferring a pattern is not the same as knowing it.</li>
</ol>
<p>Ingalls’ next sentence is also true and should also be said: “Nevertheless, in what follows we will rarely encounter differential equation models for which analytic solutions can be derived.” Both halves hold at once. Simulation does not replace analysis; it is what is left when analysis is unavailable.</p>
<hr>
</section>
<section id="this-weeks-practical" class="level2">
<h2 class="anchored" data-anchor-id="this-weeks-practical">This week’s practical</h2>
<p><code>notebooks/02_simple_networks.ipynb</code>, runnable directly in Google Colab. It covers the conservation half of this lecture: four worked examples (decay, production and decay, irreversible conversion, reversible conversion), each with a printed conservation or steady-state check, then three exercises with decreasing scaffolding — a chain <span class="math inline">\(A \to B \to C\)</span>, production plus reversible conversion (no conservation, new steady state), and competing decay pathways, where you get only a description and write the whole cell. Exercise 3’s prediction <span class="math inline">\(Q_\infty/P_\infty = k_2/k_1\)</span> is a good use of the “exact, structural” idea above.</p>
<p>Part 3 lives in <strong>Example V</strong> (Euler against the exact decay solution at four step sizes, plus the <code>linspace</code>-not-<code>arange</code> mesh rule) and <strong>Exercise 4</strong> (derive from <span class="math inline">\(A_{i+1}=(1-k_dh)A_i\)</span> where Euler oscillates and where it blows up, then check it). Both use <span class="math inline">\(k_d = 1\)</span> rather than the <span class="math inline">\(\dot a = -a\)</span> phrasing above, which is the same model.</p>
<p><strong>Not yet in a notebook:</strong> the left-nullspace computation (Part 2) — work it from the code in these notes.</p>
<p>Keep the same habit as <code>02_simple_networks.ipynb</code>: <strong>print one check, then draw the plot.</strong> A smooth curve is not evidence of a correct one.</p>
</section>
<section id="three-sentences-to-carry-into-l05" class="level2">
<h2 class="anchored" data-anchor-id="three-sentences-to-carry-into-l05">Three sentences to carry into L05</h2>
<ol type="1">
<li>A conservation is exact, structural, and free.</li>
<li>Reducing with one is rewriting, not approximating.</li>
<li>A numerical answer’s accuracy is something you chose, whether or not you thought about it.</li>
</ol>
<p>Next week, mass action stops being the right rate law for the reactions that matter most inside a cell. What rescues it is an enzyme conservation — sentences 1 and 2 above, put to real work — plus one further reduction that, unlike today’s, genuinely is a bet.</p>
</section>
<section id="sources" class="level2">
<h2 class="anchored" data-anchor-id="sources">Sources</h2>
<p>Ingalls Ch. 2 §2.1.3, pp.&nbsp;26–29 (Examples III and IV, equations 2.11–2.13; the remark on conservations, p.&nbsp;29; Exercises 2.1.7, 2.1.8) and §2.1.4, pp.&nbsp;30–33 (Figure 2.7, equation 2.16). See ingalls ch02 reaction networks.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../lecture_notes/L03-reaction-networks-and-mass-action/notes.html" class="pagination-link" aria-label="L03 — Reaction Networks and Mass Action">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">L03 — Reaction Networks and Mass Action</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../lecture_notes/L05-enzyme-kinetics-i/notes.html" class="pagination-link" aria-label="L05 — Enzyme Kinetics I: the mechanism and the Michaelis-Menten equation">
        <span class="nav-page-text"><span class="chapter-title">L05 — Enzyme Kinetics I: the mechanism and the Michaelis-Menten equation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/lab-biotek-bio-ugm/TKBM262615_Practicals/blob/main/lecture_notes/L04-conservation-and-numerical-simulation/notes.md" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div></div></footer></body></html>